language: bash

notifications:
  email: false

services:
  - docker

env:
  - TANGO_VER=9.3.3-rc1

script:
  - docker build --build-arg TANGO_VER=${TANGO_VER} -t tangocs/tango-cs .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag tangocs/tango-cs tangocs/tango-cs:${TANGO_VER}

deploy:
  - provider: script
    script: docker push tangocs/tango-cs:latest
    on:
      all_branches: true
  - provider: script
    script: docker push tangocs/tango-cs:${TANGO_VER}
    on:
      all_branches: true