language: bash

notifications:
  email: false

services:
  - docker

script:
  - docker build -t tangocs/tango-cs .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag tangocs/tango-cs tangocs/tango-cs:${TRAVIS_BRANCH}

deploy:
  - provider: script
    script: docker push tangocs/tango-cs:${TRAVIS_BRANCH}
    on:
      tags: true